[package]
name = "hot_reload"
version = "0.1.0"
edition = "2021"


[dependencies]
hot_reload_macro = { path = "../hot_reload_macro" }
logger = { path = "../logger" }
ecs = { path = "../ecs" }
ecs_derive = { path = "../ecs_derive" }
plugins = { path = "../plugins" }

libloading = "0.8.3"
