[package]
name = "hot_reload"
version = "0.1.0"
edition = "2021"


[dependencies]
hot_reload_macro = { path = "macro" }
util = { path = "../util" }
ecs = { path = "../ecs" }
app = { path = "../app" }

libloading = "0.8.3"
