[package]
name = "ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
logger = { path = "../logger" }
ecs_derive = { path = "../ecs_derive" }

libloading = "0.8.3"
itertools = "0.12.1"
fxhash = "0.2.1"
anyhow = "1.0.86"
