[package]
name = "ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
util = { path = "../util" }
ecs_macro = { path = "macro" }

fxhash.workspace = true
cgmath.workspace = true
egui = "0.28.1"

[dev-dependencies]
tracing-test = "0.2.5"
