[package]
name = "winny"
version = "0.1.0"
edition = "2021"

[lib]
name = "winny"
path = "src/lib.rs"

[workspace]
members = [
  "crates/*",
  "examples/camera",
  "examples/egui",
  "examples/particles",
  "examples/sprites",
]
exclude = ["examples", "crates/deprecated"]

[dependencies]
ecs = { path = "crates/ecs" }
audio = { path = "crates/audio" }
log = { path = "crates/log" }
util = { path = "crates/util" }
app = { path = "crates/app" }
winny_math = { path = "crates/winny_math" }
asset = { path = "crates/asset" }
gfx = { path = "crates/gfx" }
hot_reload = { path = "crates/hot_reload", optional = true }

[features]
hot_reload = ["dep:hot_reload"]
egui = ["gfx/egui"]
text = ["gfx/text"]
gilrs = ["app/controller"]
