[package]
name = "winny"
version = "0.1.0"
edition = "2021"

[lib]
name = "winny"
path = "src/lib.rs"

[workspace]
members = ["crates/*"]

[dependencies]
winny_engine = { path = "crates/winny_engine" }

