[package]
name = "winny"
version = "0.1.0"
edition = "2021"

[lib]
name = "winny"
path = "src/lib.rs"

[workspace]
members = ["crates/*"]
exclude = ["crates/deprecated", "crates/audio"]

[dependencies]
ecs = { path = "crates/ecs" }
logger = { path = "crates/logger" }
app = { path = "crates/app" }
winny_math = { path = "crates/winny_math" }
asset = { path = "crates/asset" }

window = { path = "crates/window", optional = true }
gfx = { path = "crates/gfx", optional = true }
hot_reload = { path = "crates/hot_reload", optional = true }
audio = { path = "crates/audio", optional = true }

[features]
window = ["dep:window", "dep:gfx"]
egui = ["window/egui", "gfx/egui"]
gilrs = ["window/controller"]

hot_reload = ["dep:hot_reload"]

audio = ["dep:audio"]
