[package]
name = "winny"
version = "0.1.0"
edition = "2021"

[lib]
name = "winny"
path = "src/lib.rs"

[workspace]
members = ["crates/*"]
exclude = ["crates/deprecated", "crates/audio"]

[dependencies]
ecs = { path = "crates/ecs" }
log = { path = "crates/log" }
util = { path = "crates/util" }
app = { path = "crates/app" }
winny_math = { path = "crates/winny_math" }
asset = { path = "crates/asset" }
gfx = { path = "crates/gfx" }

hot_reload = { path = "crates/hot_reload", optional = true }
audio = { path = "crates/audio", optional = true }

[features]
egui = ["gfx/egui"]
gilrs = ["app/controller"]
hot_reload = ["dep:hot_reload"]
audio = ["dep:audio"]
