[package]
name = "winny"
version = "0.1.0"
edition = "2021"

[lib]
name = "winny"
path = "src/lib.rs"

[workspace]
members = ["crates/*"]
exclude = ["crates/deprecated"]

[dependencies]
ecs = { path = "crates/ecs" }
audio = { path = "crates/audio" }
log = { path = "crates/log" }
util = { path = "crates/util" }
app = { path = "crates/app" }
winny_math = { path = "crates/winny_math" }
asset = { path = "crates/asset" }
gfx = { path = "crates/gfx" }
hot_reload = { path = "crates/hot_reload" }

[features]
egui = ["gfx/egui"]
gilrs = ["app/controller"]
