[package]
name = "winny_engine"
version = "0.1.0"
edition = "2021"


[dependencies]
ecs = { path = "../ecs" }

[dependencies.windows]
version = "0.53.0"
features = ["Win32_UI_WindowsAndMessaging", "Win32_UI_Input_KeyboardAndMouse", 
            "Win32_System_LibraryLoader", "Win32_Graphics_Gdi",
            "Win32_Graphics_OpenGL", "Win32_System_Performance",
            "Win32_System_Com", "Win32_Media_Audio_XAudio2",
            "implement"]
