[package]
name = "audio"
version = "0.1.0"
edition = "2021"

[dependencies]
util = { path = "../util" }
asset = { path = "../asset" }
app = { path = "../app" }
ecs = { path = "../ecs" }

cpal = "0.15.3"

[dev-dependencies]
tracing-test = "0.2.5"
