[package]
name = "window"
version = "0.1.0"
edition = "2021"

[dependencies]
ecs = { path = "../ecs" }
logger = { path = "../logger" }
gfx = { path = "../gfx" }
app = { path = "../app" }

winit = "0.29.15"
gilrs = { version = "0.10.3", optional = true }

[features]
egui = []
controller = ["gilrs"]
