[package]
name = "gfx"
version = "0.1.0"
edition = "2021"

[dependencies]
util = { path = "../util" }
ecs = { path = "../ecs" }
winny_math = { path = "../winny_math" }
app = { path = "../app" }
asset = { path = "../asset" }

wgpu = "0.20.1"
winit = "0.30.3"
cgmath = "0.18"
tobj = { version = "4.0.2", features = ["async"] }
image = "0.25.1"

pollster = "0.3.0"
bytemuck = { version = "1.12", features = ["derive"] }

libflate = { version = "2.1.0", optional = false }
egui = { version = "0.27.2", optional = true }
egui-wgpu = { version = "0.27.2", optional = true }
egui-winit = { version = "0.27.2", optional = true }

[features]
egui = ["dep:egui", "dep:egui-wgpu", "dep:egui-winit"]
# png = ["dep:libflate"]
