[package]
name = "gfx"
version = "0.1.0"
edition = "2021"

[dependencies]
logger = { path = "../logger" }
ecs = { path = "../ecs" }
winny_math = { path = "../winny_math" }
app = { path = "../app" }

wgpu = "0.19.3"
winit = "0.29.15"

pollster = "0.3.0"
bytemuck = { version = "1.12", features = [ "derive" ] }

libflate = { version = "2.1.0", optional = true }
egui = { version = "0.27.2", optional = true }
egui-wgpu = { version = "0.27.2", optional = true }
egui-winit = { version = "0.27.2", optional = true }

[features]
egui = ["dep:egui", "dep:egui-wgpu", "dep:egui-winit"]
png = ["dep:libflate"]
